#!/usr/bin/env python3
# 声明：本代码仅供学习和研究目的使用。使用者应遵守以下原则：
# 1. 不得用于任何商业用途。
# 2. 使用时应遵守目标平台的使用条款和robots.txt规则。
# 3. 不得进行大规模爬取或对平台造成运营干扰。
# 4. 应合理控制请求频率，避免给目标平台带来不必要的负担。
# 5. 不得用于任何非法或不当的用途。

"""
n8n 调用包装器 - 不修改原代码，动态配置参数

用法示例:
    # 爬取指定视频的评论
    python n8n_crawler_wrapper.py --video-ids "7554322613938523407,7280854932641664319" --comment-count 100

    # 爬取创作者主页
    python n8n_crawler_wrapper.py --type creator --creator-ids "MS4wLjABAAAA..." --comment-count 50

    # 关键词搜索
    python n8n_crawler_wrapper.py --type search --keywords "Python教程,编程" --comment-count 30

参数说明:
    --video-ids         视频ID列表，逗号分隔 (用于 detail 模式)
    --creator-ids       创作者ID列表，逗号分隔 (用于 creator 模式)
    --keywords          搜索关键词，逗号分隔 (用于 search 模式)
    --type              爬取类型: detail(默认) | creator | search
    --comment-count     每个视频爬取的评论数量 (默认: 10)
    --sub-comment       是否爬取二级评论: 0 或 1 (默认: 0)
    --save-option       保存方式: sqlite | json | csv | db (默认: sqlite)
    --login-type        登录方式: qrcode | phone | cookie (默认: qrcode)
    --cookies           Cookie字符串 (当 login-type=cookie 时使用)
"""

import sys
import argparse
import subprocess
import shutil
from pathlib import Path
from datetime import datetime


def backup_config(config_file: Path) -> Path:
    """备份配置文件"""
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    backup_file = config_file.with_suffix(f'.py.bak_{timestamp}')
    shutil.copy2(config_file, backup_file)
    return backup_file


def restore_config(backup_file: Path, original_file: Path):
    """恢复配置文件"""
    if backup_file.exists():
        shutil.copy2(backup_file, original_file)
        backup_file.unlink()


def update_dy_config(config_file: Path, video_ids: list, creator_ids: list):
    """更新抖音配置文件"""
    video_list = ',\n'.join(
        [f'    "{vid.strip()}"' for vid in video_ids if vid.strip()])
    creator_list = ',\n'.join(
        [f'    "{cid.strip()}"' for cid in creator_ids if cid.strip()])

    content = f'''# 声明：本代码仅供学习和研究目的使用。使用者应遵守以下原则：
# 1. 不得用于任何商业用途。
# 2. 使用时应遵守目标平台的使用条款和robots.txt规则。
# 3. 不得进行大规模爬取或对平台造成运营干扰。
# 4. 应合理控制请求频率，避免给目标平台带来不必要的负担。
# 5. 不得用于任何非法或不当的用途。
#
# 详细许可条款请参阅项目根目录下的LICENSE文件。
# 使用本代码即表示您同意遵守上述原则和LICENSE中的所有条款。

# 抖音平台配置 - Auto-generated by n8n_crawler_wrapper.py
PUBLISH_TIME_TYPE = 0

# 指定DY视频ID列表
DY_SPECIFIED_ID_LIST = [
{video_list}
]

# 指定DY用户ID列表
DY_CREATOR_ID_LIST = [
{creator_list}
]
'''
    config_file.write_text(content, encoding='utf-8')
    print(f"[OK] 已更新 dy_config.py:")
    if video_ids and any(video_ids):
        print(f"   - 视频ID: {len([v for v in video_ids if v.strip()])} 个")
    if creator_ids and any(creator_ids):
        print(f"   - 创作者ID: {len([c for c in creator_ids if c.strip()])} 个")


def update_base_config(config_file: Path, comment_count: int, sub_comment: bool, keywords: str):
    """更新基础配置文件"""
    import re

    content = config_file.read_text(encoding='utf-8')

    # 更新评论数量
    content = re.sub(
        r'(CRAWLER_MAX_COMMENTS_COUNT_SINGLENOTES\s*=\s*)\d+',
        f'\\g<1>{comment_count}',
        content
    )

    # 更新二级评论开关
    content = re.sub(
        r'(ENABLE_GET_SUB_COMMENTS\s*=\s*)(True|False)',
        f'\\g<1>{sub_comment}',
        content
    )

    # 更新关键词（如果提供）
    if keywords:
        content = re.sub(
            r'(KEYWORDS\s*=\s*)["\'].*?["\']',
            f'\\g<1>"{keywords}"',
            content
        )

    config_file.write_text(content, encoding='utf-8')
    print(f"[OK] 已更新 base_config.py:")
    print(f"   - 评论数量: {comment_count}")
    print(f"   - 二级评论: {'开启' if sub_comment else '关闭'}")
    if keywords:
        print(f"   - 搜索关键词: {keywords}")


def main():
    parser = argparse.ArgumentParser(
        description='MediaCrawler n8n 包装器 - 动态配置抖音爬虫参数',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )

    # 爬取目标参数
    parser.add_argument('--video-ids', default='',
                        help='视频ID列表，逗号分隔 (用于 detail 模式)')
    parser.add_argument('--creator-ids', default='',
                        help='创作者ID列表，逗号分隔 (用于 creator 模式)')
    parser.add_argument('--keywords', default='',
                        help='搜索关键词，逗号分隔 (用于 search 模式)')

    # 爬取类型
    parser.add_argument('--type', default='detail', choices=['detail', 'creator', 'search'],
                        help='爬取类型: detail(视频详情) | creator(创作者主页) | search(关键词搜索)')

    # 爬取配置
    parser.add_argument('--comment-count', type=int, default=10,
                        help='每个视频爬取的评论数量 (默认: 10)')
    parser.add_argument('--sub-comment', type=int, default=0, choices=[0, 1],
                        help='是否爬取二级评论: 0(否) | 1(是) (默认: 0)')

    # 保存配置
    parser.add_argument('--save-option', default='sqlite',
                        choices=['sqlite', 'json', 'csv', 'db'],
                        help='数据保存方式 (默认: sqlite)')

    # 登录配置
    parser.add_argument('--login-type', default='qrcode',
                        choices=['qrcode', 'phone', 'cookie'],
                        help='登录方式 (默认: qrcode)')
    parser.add_argument('--cookies', default='',
                        help='Cookie字符串 (当 login-type=cookie 时使用)')

    # 其他选项
    parser.add_argument('--dry-run', action='store_true',
                        help='仅显示配置，不实际执行爬虫')
    parser.add_argument('--keep-config', action='store_true',
                        help='保留修改后的配置文件，不自动恢复')

    args = parser.parse_args()

    # 验证参数
    if args.type == 'detail' and not args.video_ids:
        parser.error("--type detail 需要提供 --video-ids 参数")
    if args.type == 'creator' and not args.creator_ids:
        parser.error("--type creator 需要提供 --creator-ids 参数")
    if args.type == 'search' and not args.keywords:
        parser.error("--type search 需要提供 --keywords 参数")

    # 获取项目根目录
    project_root = Path(__file__).parent.absolute()
    config_dir = project_root / 'config'

    dy_config = config_dir / 'dy_config.py'
    base_config = config_dir / 'base_config.py'

    # 检查配置文件是否存在
    if not dy_config.exists() or not base_config.exists():
        print(f"[ERROR] 错误: 配置文件不存在！", file=sys.stderr)
        print(f"   请确保在项目根目录 {project_root} 下执行此脚本", file=sys.stderr)
        return 1

    print("=" * 60)
    print("[START] MediaCrawler n8n 包装器")
    print("=" * 60)
    print(f"[DIR] 项目路径: {project_root}")
    print(f"[TYPE] 爬取类型: {args.type}")
    print(f"[SAVE] 保存方式: {args.save_option}")
    print(f"[LOGIN] 登录方式: {args.login_type}")
    print("=" * 60)

    # 备份配置文件
    dy_backup = None
    base_backup = None

    try:
        print("\n[BACKUP] 正在备份配置文件...")
        dy_backup = backup_config(dy_config)
        base_backup = backup_config(base_config)
        print(f"   [OK] dy_config.py -> {dy_backup.name}")
        print(f"   [OK] base_config.py -> {base_backup.name}")

        # 更新配置文件
        print("\n[CONFIG] 正在更新配置...")

        # 更新抖音配置
        video_list = args.video_ids.split(',') if args.video_ids else []
        creator_list = args.creator_ids.split(',') if args.creator_ids else []
        update_dy_config(dy_config, video_list, creator_list)

        # 更新基础配置
        update_base_config(
            base_config,
            args.comment_count,
            bool(args.sub_comment),
            args.keywords
        )

        if args.dry_run:
            print("\n[WARN] Dry-run 模式: 仅显示配置，不执行爬虫")
            print("\n配置已更新，可以手动检查以下文件:")
            print(f"   - {dy_config}")
            print(f"   - {base_config}")
            return 0

        # 构建执行命令
        print("\n[CRAWL] 正在执行爬虫...")
        print("-" * 60)

        cmd = [
            'uv', 'run', 'main.py',
            '--platform', 'dy',
            '--lt', args.login_type,
            '--type', args.type,
            '--get_comment', '1',
            '--get_sub_comment', str(args.sub_comment),
            '--save_data_option', args.save_option
        ]

        # 如果是 cookie 登录，添加 cookies 参数
        if args.login_type == 'cookie' and args.cookies:
            cmd.extend(['--cookies', args.cookies])

        # 如果是搜索模式，添加关键词参数
        if args.type == 'search' and args.keywords:
            cmd.extend(['--keywords', args.keywords])

        print(f"[CMD] 执行命令: {' '.join(cmd)}")
        print("-" * 60)

        # 执行爬虫
        result = subprocess.run(
            cmd,
            cwd=project_root,
            text=True,
            encoding='utf-8'
        )

        print("-" * 60)
        if result.returncode == 0:
            print("[OK] 爬虫执行成功！")
        else:
            print(f"[ERROR] 爬虫执行失败，退出码: {result.returncode}", file=sys.stderr)

        return result.returncode

    except KeyboardInterrupt:
        print("\n\n[WARN] 用户中断执行 (Ctrl+C)")
        return 130

    except Exception as e:
        print(f"\n[ERROR] 发生错误: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        return 1

    finally:
        # 恢复配置文件（除非指定保留）
        if not args.keep_config:
            print("\n[RESTORE] 正在恢复配置文件...")
            if dy_backup:
                restore_config(dy_backup, dy_config)
                print(f"   [OK] 已恢复 dy_config.py")
            if base_backup:
                restore_config(base_backup, base_config)
                print(f"   [OK] 已恢复 base_config.py")
        else:
            print("\n[WARN] 保留配置: 配置文件未恢复，备份文件:")
            if dy_backup:
                print(f"   - {dy_backup}")
            if base_backup:
                print(f"   - {base_backup}")

        print("\n" + "=" * 60)
        print("[DONE] 执行完成")
        print("=" * 60)


if __name__ == '__main__':
    sys.exit(main())
